/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2020-05-11 06:02:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.backend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import tcms.configuration.*;

public final class library_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("tcms.configuration");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


response.setHeader("Cache-control", "no-cache");
response.setHeader("Cache-control", "no-store");
response.setHeader("Pragma", "no-cache");
response.setDateHeader("Expire",0);

if (session.getAttribute("userID") != null && session.getAttribute("roleID").equals("3") ) {

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Start header -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/header.jsp", out, false);
      out.write("\n");
      out.write("<!-- End header -->\n");
      out.write("\n");
      out.write("<!-- Start Top header View -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/topView.jsp", out, false);
      out.write("\n");
      out.write("<!-- End Top Header View -->\n");
      out.write("\n");
      out.write("<!-- Start SideBar View -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/sideView.jsp", out, false);
      out.write("\n");
      out.write("<!-- End SideBar View -->\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("function getContentInfo(val){\n");
      out.write("\t\n");
      out.write("\tvar id = val;\n");
      out.write("\t $.ajax({\n");
      out.write("\t     type: \"post\",\n");
      out.write("\t      url: \"actions/components/libraryAction.jsp\", //this is my servlet\n");
      out.write("\t       data: {\n");
      out.write("\t    \t   id: id,\n");
      out.write("\t    \t   \n");
      out.write("\t           }, \n");
      out.write("\t          success: function(msg){  \n");
      out.write("\t        \t  \n");
      out.write("\t        \t  var array = msg.split('|');\n");
      out.write("\t        \t \n");
      out.write("\t\t\t\t  var values = {\n");
      out.write("\t\t\t\t\t\t    date: array[0],\n");
      out.write("\t\t\t\t\t\t    description: array[1],\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t  };\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t  var table = document.getElementById(\"content_description\");\n");
      out.write("\t\t\t\t \n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t  Object.keys(values).forEach(function (key) {\n");
      out.write("\t\t\t\t    table.getElementsByClassName(key + \"Row\")[0]\n");
      out.write("\t\t\t\t      .getElementsByClassName(\"value\")[0]\n");
      out.write("\t\t\t\t      .textContent = values[key];\n");
      out.write("\t\t\t\t  });\n");
      out.write("\t          }\n");
      out.write("\t     });\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<main class=\"main\">\n");
      out.write("         <!-- Breadcrumb-->\n");
      out.write("         <ol class=\"breadcrumb\">\n");
      out.write("          <li class=\"breadcrumb-item\">Home</li>\n");
      out.write("          <li class=\"breadcrumb-item\">\n");
      out.write("            Components\n");
      out.write("          </li>   \n");
      out.write("          <li class=\"breadcrumb-item\">\n");
      out.write("            <a href=\"library.jsp\">Library</a>\n");
      out.write("          </li>   \n");
      out.write("        </ol>        \n");
      out.write("        <!-- Breadcrumb-->\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("          <div class=\"animated fadeIn\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-sm-12 col-xl-12\">\n");
      out.write("                \n");
      out.write("\t\t\t\t\t<div class=\"card\">\n");
      out.write("\t\t\t\t\t  <div class=\"card-header\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-align-justify\"></i> Saved files\n");
      out.write("\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t  <div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t<div id=\"exampleAccordion\" data-children=\".item\">\n");
      out.write("\t\t\t\t\t\t  <div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<a data-toggle=\"collapse\" data-parent=\"#exampleAccordion\" href=\"#exampleAccordion2019\" aria-expanded=\"true\" aria-controls=\"exampleAccordion2\">Television Files</a>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse show\" id=\"exampleAccordion2019\" role=\"tabpanel\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row mt-3\">\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t<!-- Get the video files from the library table -->\n");
      out.write("                             ");

                                String userID = session.getAttribute("userID").toString();
								java.util.List<Library> list = Library.GetTVLibrarylList(userID);
	                           
	                            for(int i=0; i<list.size(); i++) { 
	                          	 
                            
      out.write("\n");
      out.write("\n");
      out.write("                                    <div class=\"col-sm-12 col-lg-4\"> \n");
      out.write("                                        <div class=\"card\">\n");
      out.write("                                            <div class=\"card-body text-center\">\n");
      out.write("                                 \n");
      out.write("                                                <video controls > \n");
      out.write("                                                \n");
      out.write("                                                <source src=\"../../");
 out.print(list.get(i).getFileName()); 
      out.write("\" type=\"video/mp4\">\n");
      out.write("                                                </video>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"card-footer\">\n");
      out.write("                                                <div class=\"row\">\n");
      out.write("                                                    <div class=\"col-10\"><strong>Content: </strong> ");
 out.print(list.get(i).getChannelName()); 
      out.write("</div>\n");
      out.write("                                                    <div class=\"col-2\"><a class=\"icon-arrow-down-circle icons\" href=\"../../");
 out.print(list.get(i).getFileName()); 
      out.write("\" title=\"download\" download=\"");
 out.print(list.get(i).getFileName()); 
      out.write("\"></a></div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"row\">\n");
      out.write("                                                    <div class=\"col-10\"><strong>Title: </strong> ");
 out.print(list.get(i).getClipName()); 
      out.write("</div>\n");
      out.write("                                                 <!--   <div class=\"col-2\"><a class=\"fa fa-remove fa-lg\" href=\"#removeFileModal\" data-toggle=\"modal\" title=\"REMOVE\"></a></div> -->\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"row\">\n");
      out.write("                                                    <div class=\"col-10\"><strong>Duration: </strong>");
 out.print(list.get(i).getClipDuration()); 
      out.write("</div>\n");
      out.write("                                                    <div class=\"col-2\">\n");
      out.write("                                                    <a class=\"icon-info icons\" href=\"#infoModal\" id=\"");
 out.print(list.get(i).getId()); 
      out.write("\" onClick=\"getContentInfo(");
 out.print(list.get(i).getId()); 
      out.write(");\" data-toggle=\"modal\" title=\"INFO\">\n");
      out.write("                                                    \n");
      out.write("                                                    </a></div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                  \n");
      out.write("\n");
      out.write("                                \n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("  </div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t  <div class=\"item\">\n");
      out.write("\t\t\t\t\t\t\t<a data-toggle=\"collapse\" data-parent=\"#exampleAccordion\" href=\"#exampleAccordion2018\" aria-expanded=\"false\" aria-controls=\"exampleAccordion2\">Radio Files</a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse\" id=\"exampleAccordion2018\" role=\"tabpanel\">\n");
      out.write("\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t  <div class=\"row mt-3\">\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<!-- Get The audio file from the library table -->\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t ");

								java.util.List<Library> audiolist = Library.GetAudioLibrarylList(userID); 
	                           
	                            for(int i=0; i<audiolist.size(); i++) { 
	                          	 
                            
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-12 col-lg-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"card\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"card-body text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<audio controls> <source src=\"../../");
 out.print(audiolist.get(i).getFileName()); 
      out.write("\" type=\"audio/mp3\" preload=\"auto\"></audio>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"card-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-10\"><strong>Content:</strong> ");
 out.print(audiolist.get(i).getChannelName()); 
      out.write("</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-2\"><a class=\"icon-arrow-down-circle icons\" href=\"../../");
 out.print(audiolist.get(i).getFileName()); 
      out.write("\" title=\"download\" download=\"");
 out.print(audiolist.get(i).getFileName()); 
      out.write("\"></a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-10\"><strong>Title:</strong> ");
 out.print(audiolist.get(i).getClipName()); 
      out.write("</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- \t\t<div class=\"col-2\"><a class=\"fa fa-remove fa-lg\" href=\"#removeFileModal\" data-toggle=\"modal\" title=\"REMOVE\"></a></div>  -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-10\"><strong>Duration:</strong> ");
 out.print(audiolist.get(i).getClipDuration()); 
      out.write("</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t   <div class=\"col-2\">\n");
      out.write("                                                    <a class=\"icon-info icons\" href=\"#infoModal\" id=\"");
 out.print(audiolist.get(i).getId()); 
      out.write("\" onClick=\"getContentInfo(");
 out.print(audiolist.get(i).getId()); 
      out.write(");\" data-toggle=\"modal\" title=\"INFO\">\n");
      out.write("                                                    \n");
      out.write("                                                    </a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t  ");
 } 
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t  </div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("             \n");
      out.write("\t\t\t\t</div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </main>\n");
      out.write("      \n");
      out.write("      <!-- Start AsideMenu View -->\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t  <!-- End AsideMenu View --> \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("\n");
      out.write(" <!-- Start Remove Modal -->\n");
      out.write(" \t<div class=\"modal fade\" id=\"removeFileModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-danger\" role=\"document\">\n");
      out.write("              <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                  <h4 class=\"modal-title\">Video title</h4>\n");
      out.write("                  <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                    <span aria-hidden=\"true\">X</span>\n");
      out.write("                  </button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <p>Are you sure you want to <strong>remove</strong> this file?</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-footer\">\n");
      out.write("                  <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                  <button class=\"btn btn-danger\" type=\"submit\">Remove</button>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <!-- /.modal-content-->\n");
      out.write("            </div>\n");
      out.write("            <!-- /.modal-dialog-->\n");
      out.write("          </div>\n");
      out.write(" <!-- End Remove Modal -->\n");
      out.write(" \n");
      out.write("  <!-- Start Info Modal -->\n");
      out.write(" \t<div class=\"modal fade\" id=\"infoModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog modal-primary\" role=\"document\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h4 class=\"modal-title\">Info</h4>\n");
      out.write("                <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                <span aria-hidden=\"true\">X</span>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                \n");
      out.write("              <table id=\"content_description\" class=\"table table-striped table-no-bordered table-hover\" cellspacing=\"0\" width=\"100%\" style=\"width:100%\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t <tr class=\"dateRow\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><strong> Date</strong></td>\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td colspan='2' class=\"value\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr class=\"descriptionRow\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><strong> Content Description</strong></td>\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td colspan='2' class=\"value\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t                    </table>  \n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Close</button>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.modal-content-->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.modal-dialog-->\n");
      out.write("    </div>\n");
      out.write(" <!-- End Info Modal -->\n");
      out.write("\n");
      out.write("<!-- Start Footer View -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/footer.jsp", out, false);
      out.write("\n");
      out.write("<!-- End Footer View -->\n");
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>\n");
      out.write("      ");

} else {
	session.setAttribute("userID", null);
	session.setAttribute("fullName", null);
	session.setAttribute("roleID", null);
	session.setAttribute("roleDescription", null);
	session.setAttribute("email", null);
	session.setAttribute("username", null);
    session.invalidate();
	response.sendRedirect("index.jsp");
}

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
