/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2020-04-02 10:56:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.backend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import tcms.configuration.*;
import tcms.presentation.*;
import tcms.errorLogs.*;
import java.util.*;
import java.io.*;
import tcms.csp.*;

public final class programLineup_005fstatus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("tcms.errorLogs");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("tcms.presentation");
    _jspx_imports_packages.add("tcms.configuration");
    _jspx_imports_packages.add("tcms.csp");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


response.setHeader("Cache-control", "no-cache");
response.setHeader("Cache-control", "no-store");
response.setHeader("Pragma", "no-cache");
response.setDateHeader("Expire",0);

if (session.getAttribute("userID") != null && session.getAttribute("roleID").equals("3") ) {

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!-- Start header -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/header.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End header -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start Top header View -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/topView.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Top Header View -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start SideBar View -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/sideView.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End SideBar View -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function getProgramLineUp(){\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({ \r\n");
      out.write("\t     type: \"GET\",\r\n");
      out.write("\t      url: \"actions/configuration/getProgramLineStatus.jsp\", //this is my servlet\r\n");
      out.write("\t      dataType: \"json\",\r\n");
      out.write("\t       data: {\r\n");
      out.write("\t           }, \r\n");
      out.write("\t\t          success: function(applicationList){  \r\n");
      out.write("\t\t        \t \r\n");
      out.write("\t\t\t          var s = '';\r\n");
      out.write("\t\t\t          s += '<div class=\"fresh-datatables\">';\r\n");
      out.write("\t\t\t          s += '<table id=\"datatables\" class=\"table table-striped table-no-bordered table-hover\" cellspacing=\"0\" width=\"100%\" style=\"width:100%\">';\r\n");
      out.write("\t\t\t          s += '<thead>';\r\n");
      out.write("\t\t\t          s += '<tr>';\r\n");
      out.write("\t\t\t          s += '<th>ID</th>';\r\n");
      out.write("\t\t\t          s += '<th>Channel Name</th>';\r\n");
      out.write("\t\t\t          s += '<th>Day</th>';\r\n");
      out.write("\t\t\t          s += '<th>Request Date</th>';\r\n");
      out.write("\t\t\t          s += '<th>Status</th>';\r\n");
      out.write("\t\t\t          s += '<th>Actions</th>';\r\n");
      out.write("\t\t\t          s += '</tr>';\r\n");
      out.write("\t\t\t          s += '</thead>';\r\n");
      out.write("\t\t\t          s += '<tfoot>';\r\n");
      out.write("\t\t\t          s += '<tr>';\r\n");
      out.write("\t\t\t          s += '<th>ID</th>';\r\n");
      out.write("\t\t\t          s += '<th>Channel Name</th>';\r\n");
      out.write("\t\t\t          s += '<th>Day</th>';\r\n");
      out.write("\t\t\t          s += '<th>Request Date</th>';\r\n");
      out.write("\t\t\t          s += '<th>Status</th>';\r\n");
      out.write("\t\t\t          s += '<th>Actions</th>';\r\n");
      out.write("\t\t\t          s += '</tr>';\r\n");
      out.write("\t\t\t          s += '</tfoot>';\r\n");
      out.write("\t\t\t          s += '<tbody >';\r\n");
      out.write("\t\t\t          $.each(applicationList.data, function(index,applicationList) {  \r\n");
      out.write("\t\t\t                s += '<tr>';\r\n");
      out.write("\t\t\t\t\t\t    s += '<td>' + applicationList.applicationID + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + applicationList.channelName + '<input type=\"hidden\" id=\"channelName\" value=\"'+ applicationList.channelName +'\"></td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + applicationList.day + '<input type=\"hidden\" id=\"dayName\" value=\"'+ applicationList.day +'\"></td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + applicationList.entryDate + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\t//s += '<td>' + applicationList.flag + '</td>';\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td> <span class=\"badge badge-danger\" style=\"font-size:15px;\">' + applicationList.flag + '</span></td>';\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td> <a class=\"btn btn-primary btn-circle btn-sm\" href=\"#viewChangeRequestModal\" data-toggle=\"modal\" title=\"View\"  onClick=\"viewComment('+ applicationList.applicationID +');\" ><i class=\"fa fa-book\"></i></a>&nbsp; <a class=\"btn btn-warning btn-circle btn-sm\" href=\"#previewProgramLineup\" data-toggle=\"modal\" title=\"Preview\"  onClick=\"approveProgramLineUp(' + applicationList.applicationID +');\"><i class=\"fa fa-eye\"></i></a></td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '</tr>';\r\n");
      out.write("\t\t\t          });\t\r\n");
      out.write("\t\t\t          //',' + applicationList.channelName + ',' + applicationList.day \r\n");
      out.write("\t\t\t          s += '</tbody>';\r\n");
      out.write("\t\t\t          s += '</table>';\r\n");
      out.write("\t\t\t          s += '</div>';\r\n");
      out.write("\t\t\t          $('#result').html(s);\r\n");
      out.write("\t\t\t          $('#datatables').DataTable( {\r\n");
      out.write("\t\t\t        \t  dom: 'Bfrtip',\r\n");
      out.write("\t\t\t\t            buttons: [\r\n");
      out.write("\t\t\t\t            \t\r\n");
      out.write("\t\t\t\t                'copy', 'csv', 'excel', 'pdf', 'print'\r\n");
      out.write("\t\t\t\t                \r\n");
      out.write("\t\t\t\t            ]\r\n");
      out.write("\t\t\t           } );\r\n");
      out.write("\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t   });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function approveProgramLineUp(appID){\r\n");
      out.write("    var applicationID = appID;\r\n");
      out.write("    var channelName = document.getElementById(\"channelName\").value;\r\n");
      out.write("    var day = document.getElementById(\"dayName\").value;\r\n");
      out.write("    \r\n");
      out.write("    document.getElementById(\"applicationID\").value = applicationID;\r\n");
      out.write("     $.ajax({\r\n");
      out.write("    \t  type: \"GET\",\r\n");
      out.write("          url: \"actions/configuration/getProgramLineUp.jsp\", //this is my servlet\r\n");
      out.write("          dataType: \"json\",\r\n");
      out.write("          data: {\r\n");
      out.write("        \t   applicationID: applicationID\r\n");
      out.write("           },\r\n");
      out.write("        \t   success: function(programList){  \r\n");
      out.write("                 \r\n");
      out.write("\t\t\t          var s = '';\r\n");
      out.write("\t\t\t          s += '<div class=\"modal-header\">';\r\n");
      out.write("\t\t\t         // s += '<h4 class=\"modal-title\">Change Request Program Line up</h4>';\r\n");
      out.write("\t\t\t          s += '<h4 class=\"modal-title\">' + day + ' - ' + channelName +' Change Request Program Line up</h4>';\r\n");
      out.write("\t\t\t          s += '<button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">';\r\n");
      out.write("\t\t\t          s += '<span aria-hidden=\"true\">X</span>';\r\n");
      out.write("\t\t\t          s += '</button>';\r\n");
      out.write("\t\t\t          s += '</div>';\r\n");
      out.write("\t\t\t          s += '<div class=\"modal-body\">';\r\n");
      out.write("\t\t\t          s += '<div class=\"fresh-datatables\">';\r\n");
      out.write("\t\t\t          s += '<table id=\"datatables1\" class=\"table table-striped table-no-bordered table-hover\" cellspacing=\"0\" width=\"100%\" style=\"width:100%\">';\r\n");
      out.write("\t\t\t          s += '<thead>';\r\n");
      out.write("\t\t\t          s += '<tr>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" style=\"width:12%\">Time</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\">Name</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\">Main Objective</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\">Target Audience</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\">Expectetions</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\">Status</th>';\r\n");
      out.write("\t\t\t         \r\n");
      out.write("\t\t\t          s += '</tr>';\r\n");
      out.write("\t\t\t          s += '</thead>';\r\n");
      out.write("\t\t\t          s += '<tfoot>';\r\n");
      out.write("\t\t\t          s += '<tr>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" style=\"width:12%\">Time</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\">Name</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\">Main Objective</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\">Target Audience</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\">Expectetions</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\">Status</th>';\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t          s += '</tr>';\r\n");
      out.write("\t\t\t          s += '</tfoot>';\r\n");
      out.write("\t\t\t          s += '<tbody >';\r\n");
      out.write("\t\t\t          $.each(programList.data, function(index,programList) {\r\n");
      out.write("\t\t\t                s += '<tr>';\r\n");
      out.write("\t\t\t\t\t\t    s += '<td>' + programList.time + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + programList.programeName + ' </td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + programList.programObjective + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + programList.targetAudience + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + programList.expectedArchivement + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + programList.flag + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '</tr>';\r\n");
      out.write("\t\t\t          });\t\r\n");
      out.write("\t\t\t      \t\r\n");
      out.write("\t\t\t          s += '</tbody>';\r\n");
      out.write("\t\t\t          s += '</table>';\r\n");
      out.write("\t\t\t          s += '</div>';\r\n");
      out.write("\t\t\t          s += '</div>';\r\n");
      out.write("\t\t\t         /* s += '<div class=\"form-group\" style=\"margin-left:2%; margin-right:2%\">';\r\n");
      out.write("\t\t\t          s += '<label for=\"role-name\"><b>Remark</b></label>';\r\n");
      out.write("\t\t\t          s += '<textarea class=\"form-control\" id=\"reason\"  name=\"reason\">';\t\r\n");
      out.write("\t\t\t          s += '</textarea>';               \r\n");
      out.write("\t\t\t          s += '</div>';\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t          s += '<div class=\"modal-footer\">';\r\n");
      out.write("\t\t\t          s += '<a  data-toggle=\"modal\" href=\"#rejectRequestModal\">  <button class=\"btn btn-danger\" type=\"button\" onClick=\"rejectApplication();\"> Reject</button></a>';\r\n");
      out.write("\t\t\t          s += '<button class=\"btn btn-success\" data-toggle=\"modal\" type=\"button\" onClick=\"approveApplication();\">Approve</button>';\r\n");
      out.write("\t\t\t          s += '</div>';\r\n");
      out.write("\t\t\t          */\r\n");
      out.write("\t\t\t          $('#result2').html(s);\r\n");
      out.write("\t\t\t          $('#datatables1').DataTable( {\r\n");
      out.write("                          \"order\": [],\r\n");
      out.write("                           \"columnDefs\": [{\r\n");
      out.write("                               \"targets\": 'no-sort',\r\n");
      out.write("                               \"orderable\": false,\r\n");
      out.write("                    \t\t\t }]\r\n");
      out.write("                   \t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t   });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function approveApplication(){\r\n");
      out.write("\tvar applicationID = document.getElementById(\"applicationID\").value\r\n");
      out.write("\tvar reason = document.getElementById(\"remark\").value;\r\n");
      out.write("\tvar userID = document.getElementById(\"userID\").value;\r\n");
      out.write("\t\r\n");
      out.write("\t var day = document.getElementById(\"dayName\").value;\r\n");
      out.write("\t \r\n");
      out.write("\tif (reason == \"\") {\r\n");
      out.write("\t\talert(\"Please enter Remark to Approve the request!\");\r\n");
      out.write("\t\tdie(\"\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        type: \"post\",\r\n");
      out.write("         url: \"actions/configuration/approvePL.jsp\", //this is my servlet\r\n");
      out.write("          data: {\r\n");
      out.write("        \t  applicationID: applicationID,\r\n");
      out.write("        \t  reason: reason,\r\n");
      out.write("        \t  userID: userID,\r\n");
      out.write("        \t  day: day\r\n");
      out.write("              },\r\n");
      out.write("             success: function(msg){\r\n");
      out.write("            \t\r\n");
      out.write("            \t var response = JSON.parse(msg);\r\n");
      out.write("                 var status = response.status;\r\n");
      out.write("                 if (status == 1) {\r\n");
      out.write("                \t alert('Program Line Up successful Approved!');\r\n");
      out.write("                \t location.reload();\r\n");
      out.write("                 }else{\r\n");
      out.write("                \t alert(\"Couldn't Approve program!\");\r\n");
      out.write("                \t location.reload();\r\n");
      out.write("                 }\r\n");
      out.write("             }\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function rejectApplication(){\r\n");
      out.write("\tvar applicationID = document.getElementById(\"applicationID\").value;\r\n");
      out.write("\tvar reason = document.getElementById(\"remark\").value;\r\n");
      out.write("\tvar userID = document.getElementById(\"userID\").value;\r\n");
      out.write("\r\n");
      out.write("\tvar day = document.getElementById(\"dayName\").value;\r\n");
      out.write("\tif (reason == \"\") {\r\n");
      out.write("\t\talert(\"Please enter Remark to Reject the request!\");\r\n");
      out.write("\t\tdie(\"\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        type: \"post\",\r\n");
      out.write("         url: \"actions/configuration/rejectPL.jsp\", //this is my servlet\r\n");
      out.write("          data: {\r\n");
      out.write("        \t  applicationID: applicationID,\r\n");
      out.write("        \t  reason: reason,\r\n");
      out.write("        \t  userID:userID,\r\n");
      out.write("        \t  day: day\r\n");
      out.write("              },\r\n");
      out.write("             success: function(msg){\r\n");
      out.write("            \t\r\n");
      out.write("            \t var response = JSON.parse(msg);\r\n");
      out.write("                 var status = response.status;\r\n");
      out.write("                 if (status == 1) {\r\n");
      out.write("                \t alert('Program Line Up successful Rejected!');\r\n");
      out.write("                \t location.reload();\r\n");
      out.write("                 }else{\r\n");
      out.write("                \t alert(\"Couldn't Rejected program!\");\r\n");
      out.write("                \t location.reload();\r\n");
      out.write("                 }\r\n");
      out.write("             }\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function viewComment(appID){\r\n");
      out.write("    var applicationID = appID;\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        type: \"post\",\r\n");
      out.write("         url: \"actions/configuration/getProgramComment.jsp\", //this is my servlet\r\n");
      out.write("          data: {\r\n");
      out.write("        \t  \tapplicationID: applicationID,\r\n");
      out.write("        \t    },\r\n");
      out.write("             success: function(msg){\r\n");
      out.write("            \t\r\n");
      out.write("            \t document.getElementById(\"reason\").value = msg.trim();\r\n");
      out.write("             }\r\n");
      out.write("        });\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<input id=\"userID\" name=\"userID\" type=\"hidden\" value =\"");
 out.print(session.getAttribute("userID")); 
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"applicationID\">\r\n");
      out.write("\r\n");
      out.write("      <main class=\"main\">\r\n");
      out.write("         <!-- Breadcrumb-->\r\n");
      out.write("         <ol class=\"breadcrumb\">\r\n");
      out.write("          <li class=\"breadcrumb-item\">Home</li>\r\n");
      out.write("          <li class=\"breadcrumb-item\">\r\n");
      out.write("            Program Line up\r\n");
      out.write("          </li>   \r\n");
      out.write("          <li class=\"breadcrumb-item\">\r\n");
      out.write("            <a href=\"programLineup.jsp\">PL - Change Request</a>\r\n");
      out.write("          </li>   \r\n");
      out.write("        </ol>        \r\n");
      out.write("        <!-- Breadcrumb-->\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"animated fadeIn\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-12 col-xl-12\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-header\">\r\n");
      out.write("                    <i class=\"fa fa-align-justify\"></i>Change Request Program Line up for all Channels             \r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                   \r\n");
      out.write("\t\t\t\t\t\t<div id=\"result\"></div>                   \r\n");
      out.write(" \t\t\t\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("             \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </main>\r\n");
      out.write(" \r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("    <!-- Start View Change Request Form -->\r\n");
      out.write(" <div class=\"modal fade\" id=\"viewChangeRequestModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-primary\" role=\"document\">\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                  <h4 class=\"modal-title\">Change Request Form</h4>\r\n");
      out.write("                  <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">X</span>\r\n");
      out.write("                  </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                   \r\n");
      out.write("                    \r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"role-name\"><b>Reason for Change Request</b></label>\r\n");
      out.write("                        \t<textarea class=\"form-control\" id=\"reason\"  name=\"reason\"></textarea>                    \r\n");
      out.write("                      </div>\r\n");
      out.write("                     \r\n");
      out.write("                   \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.modal-content-->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.modal-dialog-->\r\n");
      out.write("          </div>\r\n");
      out.write("    <!-- End View Change Request Form -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("<!-- Start Preview Changed Program Line up -->        \r\n");
      out.write("      \r\n");
      out.write("        <div class=\"modal fade\" id=\"previewProgramLineup\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("          <div class=\"modal-dialog modal-primary modal-lg\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\" style=\"width:1200px; margin-left:-150px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t        <div id=\"result2\"></div>\r\n");
      out.write("\t\t\t       \r\n");
      out.write("\t\t\t       <div class=\"form-group\" style=\"margin-left:2%; margin-right:2%\">\r\n");
      out.write("\t\t\t         <label for=\"role-name\"><b>Remark</b></label>\r\n");
      out.write("\t\t\t         <textarea class=\"form-control\" id=\"remark\"  name=\"remark\"></textarea>    \r\n");
      out.write("\t\t\t                    \r\n");
      out.write("\t\t\t         </div>\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t        <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t       <button class=\"btn btn-danger\" type=\"button\" onClick=\"rejectApplication();\"> Reject</button>\r\n");
      out.write("\t\t\t         <button class=\"btn btn-success\" data-toggle=\"modal\" type=\"button\" onClick=\"approveApplication();\">Approve</button>\r\n");
      out.write("\t\t\t          </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.modal-content-->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.modal-dialog-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.end-add-user-modal-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- End Preview Changed Program Line up -->        \r\n");
      out.write("\r\n");
      out.write("<!-- Start Top header View -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Top Header View -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t    $('#datatables').DataTable( {\r\n");
      out.write("\t        dom: 'Bfrtip',\r\n");
      out.write("\t        buttons: [\r\n");
      out.write("\t            'copy', 'csv', 'excel', 'pdf', 'print'\r\n");
      out.write("\t        ]\r\n");
      out.write("\t    } );\r\n");
      out.write("\t    $('#datatables1').DataTable( {\r\n");
      out.write("\t        dom: 'Bfrtip',\r\n");
      out.write("\t        buttons: [\r\n");
      out.write("\t            'copy', 'csv', 'excel', 'pdf', 'print'\r\n");
      out.write("\t        ]\r\n");
      out.write("\t    } );\r\n");
      out.write("\t} );\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tgetProgramLineUp();\r\n");
      out.write("\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("      ");

} else {
	session.setAttribute("userID", null);
	session.setAttribute("fullName", null);
	session.setAttribute("roleID", null);
	session.setAttribute("roleDescription", null);
	session.setAttribute("email", null);
	session.setAttribute("username", null);
    session.invalidate();
	response.sendRedirect("index.jsp");
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
