/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2020-01-17 05:30:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.backend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import tcms.configuration.*;
import tcms.presentation.*;
import tcms.errorLogs.*;
import java.util.*;
import java.io.*;

public final class users_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("tcms.errorLogs");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("tcms.presentation");
    _jspx_imports_packages.add("tcms.configuration");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Start header -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/header.jsp", out, false);
      out.write("\n");
      out.write("<!-- End header -->\n");
      out.write("\n");
      out.write("<!-- Start Top header View -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/topView.jsp", out, false);
      out.write("\n");
      out.write("<!-- End Top Header View -->\n");
      out.write("\n");
      out.write("<!-- Start SideBar View -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/sideView.jsp", out, false);
      out.write("\n");
      out.write("<!-- End SideBar View -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("//START PASSWORD CHECK \n");
      out.write("function passwordCheck(field_val,fieldName){\n");
      out.write("\tif(field_val.length <= 8){\n");
      out.write("\t\t// Declare variable\n");
      out.write("      var lowercaseCheck = /.*[a-z]/\n");
      out.write("      var uppercaseCheck = /.*[A-Z]/\n");
      out.write("      var specialCharacterCheck = /.*[!@#$%^&*]/\n");
      out.write("      var digitCheck = /.*\\d/       \t\n");
      out.write("      var countDigitCheck = /.{8,}/\n");
      out.write("\n");
      out.write("      // Search to the variable        \n");
      out.write("      var regResultLowerCase = field_val.search(lowercaseCheck);             \n");
      out.write("      var regResultUpperCase = field_val.search(uppercaseCheck);\n");
      out.write("      var regResultspecialCharacter = field_val.search(specialCharacterCheck);\n");
      out.write("      var regResultDigit = field_val.search(digitCheck);\n");
      out.write("      var regResultCountCharacters = field_val.search(countDigitCheck);\n");
      out.write("\n");
      out.write("      if(regResultLowerCase != 0){\n");
      out.write("      \t$('#pmatch').empty()\n");
      out.write("      \t\t\t    .html(\"Password should contain atleast one lowercase character \")\n");
      out.write("      \t\t\t    .css(\"display\",\"block\")\n");
      out.write("      \t\t\t    .css(\"color\",\"red\")\n");
      out.write("      \t\t\t    .css(\"font-weight\",\"bold\")\n");
      out.write("      \t\t\t    .css(\"font-size\",\"14px\");    \n");
      out.write("      \tdie();\n");
      out.write("      }\n");
      out.write("      else if(regResultUpperCase != 0){        \t\n");
      out.write("      \t$('#pmatch').empty()\n");
      out.write("\t\t    \t\t\t.html(\"Password should contain atleast one uppercase character \")\n");
      out.write("\t\t    \t\t\t.css(\"display\",\"block\")\n");
      out.write("\t\t    \t\t\t.css(\"color\",\"red\")\n");
      out.write("\t\t    \t\t\t.css(\"font-weight\",\"bold\")\n");
      out.write("\t\t    \t\t\t.css(\"font-size\",\"14px\"); \n");
      out.write("      \tdie();\n");
      out.write("      }\n");
      out.write("      else if(regResultspecialCharacter != 0){        \t\n");
      out.write("      \t$('#pmatch').empty()\n");
      out.write("\t\t    \t\t\t.html(\"Password should contain atleast one special character \")\n");
      out.write("\t\t    \t\t\t.css(\"display\",\"block\")\n");
      out.write("\t\t    \t\t\t.css(\"color\",\"red\")\n");
      out.write("\t\t    \t\t\t.css(\"font-weight\",\"bold\")\n");
      out.write("\t\t    \t\t\t.css(\"font-size\",\"14px\"); \n");
      out.write("      }\n");
      out.write("      else if(regResultDigit != 0){        \t\n");
      out.write("      \t$('#pmatch').empty()\n");
      out.write("\t\t    \t\t\t.html(\"Password should contain atleast one digit \")\n");
      out.write("\t\t    \t\t\t.css(\"display\",\"block\")\n");
      out.write("\t\t    \t\t\t.css(\"color\",\"red\")\n");
      out.write("\t\t    \t\t\t.css(\"font-weight\",\"bold\")\n");
      out.write("\t\t    \t\t\t.css(\"font-size\",\"14px\"); \n");
      out.write("      \tdie();\n");
      out.write("      }\n");
      out.write("      else if(regResultCountCharacters != 0){        \t\n");
      out.write("      \t$('#pmatch').empty()\n");
      out.write("\t\t    \t\t\t.html(\"Password should contain atleast eight characters \")\n");
      out.write("\t\t    \t\t\t.css(\"display\",\"block\")\n");
      out.write("\t\t    \t\t\t.css(\"color\",\"red\")\n");
      out.write("\t\t    \t\t\t.css(\"font-weight\",\"bold\")\n");
      out.write("\t\t    \t\t\t.css(\"font-size\",\"14px\"); \n");
      out.write("      \tdie();\n");
      out.write("      }\n");
      out.write("      else{        \t\n");
      out.write("      \t$('#pmatch').empty();\n");
      out.write("      \t//registerUser();\n");
      out.write("      }\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("//END PASSWORD CHECK\n");
      out.write("\n");
      out.write("function addUser(){\n");
      out.write("\t$('#pmatch').empty();\n");
      out.write("\tvar firstname = document.getElementById('first_name').value ;\n");
      out.write("\tvar middlename = document.getElementById('middle_name').value ;\n");
      out.write("\tvar lastname = document.getElementById('last_name').value ;\n");
      out.write("\tvar email = document.getElementById('email').value;\n");
      out.write("\tvar username = document.getElementById('username').value ;\n");
      out.write("\tvar role = document.getElementById(\"role\").selectedIndex;\n");
      out.write("\tvar status = document.getElementById('status').selectedIndex;\n");
      out.write("\tvar password = document.getElementById('password').value;\n");
      out.write("\tvar confirm_password = document.getElementById('confirm_password').value;\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\tif (firstname == \"\") {\n");
      out.write("\t\talert(\"Please enter First Name!\");\n");
      out.write("\t\tdie(\"\");\n");
      out.write("\t}\n");
      out.write("\tif (lastname == \"\") {\n");
      out.write("\t\talert(\"Please enter Last Name!\");\n");
      out.write("\t\tdie(\"\");\n");
      out.write("\t}\n");
      out.write("\tif (email == \"\") {\n");
      out.write("\t\talert(\"Please enter email address!\");\n");
      out.write("\t\tdie(\"\");\n");
      out.write("\t}\n");
      out.write("\tif (username == \"\") {\n");
      out.write("\t\talert(\"Please enter username!\");\n");
      out.write("\t\tdie(\"\");\n");
      out.write("\t}\n");
      out.write("\tif (role == \"\") {\n");
      out.write("\t\talert(\"Please select Role!\");\n");
      out.write("\t\tdie(\"\");\n");
      out.write("\t}\n");
      out.write("\tif (status == \"\") {\n");
      out.write("\t\talert(\"Please select Status!\");\n");
      out.write("\t\tdie(\"\");\n");
      out.write("\t}\n");
      out.write("\tif (password == \"\") {\n");
      out.write("\t\talert(\"Please enter Password!\");\n");
      out.write("\t\tdie(\"\");\n");
      out.write("\t}\n");
      out.write("\tif(password.length >= 8){\n");
      out.write("\t\t\n");
      out.write("\t\t// Declare variable\n");
      out.write("\t  var lowercaseCheck = /.*[a-z]/\n");
      out.write("\t  var uppercaseCheck = /.*[A-Z]/\n");
      out.write("\t  var specialCharacterCheck = /.*[!@#$%^&*]/\n");
      out.write("\t  var digitCheck = /.*\\d/       \t\n");
      out.write("\t  var countDigitCheck = /.{8,}/\n");
      out.write("\n");
      out.write("\t  // Search to the variable        \n");
      out.write("\t  var regResultLowerCase = password.search(lowercaseCheck);             \n");
      out.write("\t  var regResultUpperCase = password.search(uppercaseCheck);\n");
      out.write("\t  var regResultspecialCharacter = password.search(specialCharacterCheck);\n");
      out.write("\t  var regResultDigit = password.search(digitCheck);\n");
      out.write("\t  var regResultCountCharacters = password.search(countDigitCheck);\n");
      out.write("\n");
      out.write("\t  if(regResultLowerCase != 0){\n");
      out.write("\t  \t$('#pmatch').empty()\n");
      out.write("\t  \t\t\t    .html(\"Password should contain atleast one lowercase character \")\n");
      out.write("\t  \t\t\t    .css(\"display\",\"block\")\n");
      out.write("\t  \t\t\t    .css(\"color\",\"red\")\n");
      out.write("\t  \t\t\t    .css(\"font-weight\",\"bold\")\n");
      out.write("\t  \t\t\t    .css(\"font-size\",\"14px\");    \n");
      out.write("\t  \tdie();\n");
      out.write("\t  }\n");
      out.write("\t  else if(regResultUpperCase != 0){        \t\n");
      out.write("\t  \t$('#pmatch').empty()\n");
      out.write("\t\t    \t\t\t.html(\"Password should contain atleast one uppercase character \")\n");
      out.write("\t\t    \t\t\t.css(\"display\",\"block\")\n");
      out.write("\t\t    \t\t\t.css(\"color\",\"red\")\n");
      out.write("\t\t    \t\t\t.css(\"font-weight\",\"bold\")\n");
      out.write("\t\t    \t\t\t.css(\"font-size\",\"14px\"); \n");
      out.write("\t  \tdie();\n");
      out.write("\t  }\n");
      out.write("\t  else if(regResultspecialCharacter != 0){        \t\n");
      out.write("\t  \t$('#pmatch').empty()\n");
      out.write("\t\t    \t\t\t.html(\"Password should contain atleast one special character \")\n");
      out.write("\t\t    \t\t\t.css(\"display\",\"block\")\n");
      out.write("\t\t    \t\t\t.css(\"color\",\"red\")\n");
      out.write("\t\t    \t\t\t.css(\"font-weight\",\"bold\")\n");
      out.write("\t\t    \t\t\t.css(\"font-size\",\"14px\"); \n");
      out.write("\t  \tdie();\n");
      out.write("\t  }\n");
      out.write("\t  else if(regResultDigit != 0){        \t\n");
      out.write("\t  \t$('#pmatch').empty()\n");
      out.write("\t\t    \t\t\t.html(\"Password should contain atleast one digit \")\n");
      out.write("\t\t    \t\t\t.css(\"display\",\"block\")\n");
      out.write("\t\t    \t\t\t.css(\"color\",\"red\")\n");
      out.write("\t\t    \t\t\t.css(\"font-weight\",\"bold\")\n");
      out.write("\t\t    \t\t\t.css(\"font-size\",\"14px\"); \n");
      out.write("\t  \tdie();\n");
      out.write("\t  }\n");
      out.write("\t  else if(regResultCountCharacters != 0){        \t\n");
      out.write("\t  \t$('#pmatch').empty()\n");
      out.write("\t\t    \t\t\t.html(\"Password should contain atleast eight characters \")\n");
      out.write("\t\t    \t\t\t.css(\"display\",\"block\")\n");
      out.write("\t\t    \t\t\t.css(\"color\",\"red\")\n");
      out.write("\t\t    \t\t\t.css(\"font-weight\",\"bold\")\n");
      out.write("\t\t    \t\t\t.css(\"font-size\",\"14px\"); \n");
      out.write("\t  \tdie();\n");
      out.write("\t  }\n");
      out.write("\t  else{        \t\n");
      out.write("\t  \t$('#pmatch').empty();\n");
      out.write("\t  \t//registerUser();\n");
      out.write("\t  }\n");
      out.write("\t  \n");
      out.write("\t  if (password == confirm_password) {\n");
      out.write("\n");
      out.write("\t\t  var answer = confirm(\"Please confirm to register!\")\n");
      out.write("\t\t  if (answer) {\n");
      out.write("\t\t  \t\n");
      out.write("\t\t  \t//document.getElementById(\"overlay\").style.display = \"block\";\n");
      out.write("\t\t  \t\n");
      out.write("\t\t   $.ajax({\n");
      out.write("\t\t       type: \"post\",\n");
      out.write("\t\t        url: \"addStaff.jsp\", //this is my servlet\n");
      out.write("\t\t         data: {\n");
      out.write("\t\t      \t  firstname: firstname, \n");
      out.write("\t\t      \t  middlename: middlename,\n");
      out.write("\t\t  \t\t  lastname: lastname,\n");
      out.write("\t\t  \t\t  email: email,\n");
      out.write("\t\t  \t\t  username: username,\n");
      out.write("\t\t  \t\t  password: password,\n");
      out.write("\t\t  \t\t  role:role,\n");
      out.write("\t\t  \t\t  status:status\n");
      out.write("\t\t             }, \n");
      out.write("\t\t            success: function(msg){      \n");
      out.write("\t\t            \tvar response = JSON.parse(msg);\n");
      out.write("\t\t                var status = response.status;\n");
      out.write("\t\t                if (status == 1) {\n");
      out.write("\t\t                    alert(\"Staff Information Successfully Added !\");\n");
      out.write("\t\t                    \n");
      out.write("\t\t                    document.getElementById('first_name').value = \"\";\n");
      out.write("\t\t                    document.getElementById('middle_name').value =\"\";\n");
      out.write("\t\t        \t\t\tdocument.getElementById('last_name').value =\"\";\n");
      out.write("\t\t        \t\t\tdocument.getElementById('email').value = \"\";\n");
      out.write("\t\t        \t\t\tdocument.getElementById('username').value = \"\";\n");
      out.write("\t\t        \t\t\tdocument.getElementById(\"role\").value=\"\";\n");
      out.write("\t\t        \t\t\tdocument.getElementById('status').value = \"\";\n");
      out.write("\t\t        \t\t\tdocument.getElementById('password').value = \"\";\n");
      out.write("\t\t        \t\t\tdocument.getElementById('confirm_password').value = \"\";\n");
      out.write("\t\t                    location.reload();\n");
      out.write("\t\t                    } else {\n");
      out.write("\t\t                    alert(\"Error! Couldn't Add Staff Information... \");\n");
      out.write("\t\t                }\n");
      out.write("\t\t          }\n");
      out.write("\t\t       });\n");
      out.write("\n");
      out.write("\t\t  } else {\n");
      out.write("\t\t  \talert(\"Registration was cancelled!\");\n");
      out.write("\t\t  }\n");
      out.write("\n");
      out.write("\t\t  } else {\n");
      out.write("\t\t\t  $('#pmatch').empty()\n");
      out.write("\t\t\t    .html(\"Password does not match \")\n");
      out.write("\t\t\t\t.css(\"display\",\"block\")\n");
      out.write("\t\t\t\t.css(\"color\",\"red\")\n");
      out.write("\t\t\t\t.css(\"font-weight\",\"bold\")\n");
      out.write("\t\t\t\t.css(\"font-size\",\"14px\"); \n");
      out.write("\t\t  \tdocument.getElementById(\"pmatch\").style.display = \"block\";\n");
      out.write("\t\t  \t\n");
      out.write("\t\t  }\n");
      out.write("\t}else{\n");
      out.write("\t\t$('#pmatch').empty()\n");
      out.write("\t\t.html(\"Password should contain atleast eight characters \")\n");
      out.write("\t\t.css(\"display\",\"block\")\n");
      out.write("\t\t.css(\"color\",\"red\")\n");
      out.write("\t\t.css(\"font-weight\",\"bold\")\n");
      out.write("\t\t.css(\"font-size\",\"14px\"); \n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("      <main class=\"main\">\n");
      out.write("        <!-- Breadcrumb-->\n");
      out.write("        <ol class=\"breadcrumb\">\n");
      out.write("          <li class=\"breadcrumb-item\">Home</li>\n");
      out.write("          <li class=\"breadcrumb-item\">\n");
      out.write("            Settings\n");
      out.write("          </li>\n");
      out.write("          <li class=\"breadcrumb-item active\">\n");
      out.write("            <a href=\"users.jsp\">Users</a>\n");
      out.write("          </li>\n");
      out.write("        </ol>\n");
      out.write("\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("          <div class=\"animated fadeIn\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-12 col-xl-12\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                  <div class=\"card-header\">\n");
      out.write("                    <i class=\"fa fa-align-justify\"></i> System Users            \n");
      out.write("                    <div class=\"card-header-actions\">\n");
      out.write("                      <button class=\"btn btn-pill btn-block btn-primary\" type=\"button\" data-toggle=\"modal\" data-target=\"#addUserModal\">\n");
      out.write("                       <i class=\"fa fa-plus\"></i>\n");
      out.write("                        <b>Add User</b>\n");
      out.write("                      </button>\n");
      out.write("                      </a>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"card-body\">\n");
      out.write("                    <div class=\"toolbar\"></div>                   \n");
      out.write("                    <div class=\"fresh-datatables\">\n");
      out.write("                    <table id=\"datatables\" class=\"table table-striped table-no-bordered table-hover\" cellspacing=\"0\" width=\"100%\" style=\"width:100%\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>Full Name</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>Email</th>\n");
      out.write("                        <th>Role</th>\n");
      out.write("                        <th>Status</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"disabled-sorting\">Actions</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tfoot>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("                        <th>Full Name</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>Email</th>\n");
      out.write("                        <th>Role</th>\n");
      out.write("                        <th>Status</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"disabled-sorting\">Actions</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tfoot>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t          <!-- Start of the Table Body -->\t\n");
      out.write("\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Roger P. Njau</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>roger.njau@trca.go.tz</td>\n");
      out.write("                        <td>Administrator</td>\n");
      out.write("                        <td> <span class=\"badge badge-success\">Active</span> </td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>                       \n");
      out.write("                        <a class=\"btn btn-success\" title=\"VIEW\" data-toggle=\"modal\" data-target=\"#viewUserModal\">\n");
      out.write("                          <i class=\"fa fa-search-plus\"></i>\n");
      out.write("                        </a>\n");
      out.write("                         \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-info\" title=\"EDIT\" data-toggle=\"modal\" data-target=\"#editUserModal\">\n");
      out.write("                          <i class=\"fa fa-edit\"></i>\n");
      out.write("                        </a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\t\n");
      out.write("\n");
      out.write("                      <tr>\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Ibrahim I. Ibrahim</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>ibrahim.ibrahim@trca.go.tz</td>\n");
      out.write("                        <td>Senior operator</td>\n");
      out.write("                        <td> <span class=\"badge badge-danger\">Inactive</span> </td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>                       \n");
      out.write("                        <a class=\"btn btn-success\" title=\"VIEW\" data-toggle=\"modal\" data-target=\"#viewUserModal\">\n");
      out.write("                          <i class=\"fa fa-search-plus\"></i>\n");
      out.write("                        </a>\n");
      out.write("                         \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-info\" title=\"EDIT\" data-toggle=\"modal\" data-target=\"#editUserModal\">\n");
      out.write("                          <i class=\"fa fa-edit\"></i>\n");
      out.write("                        </a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- End of the Table Body -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   </tbody>\n");
      out.write("\t\t\t\t\t\t\t\t\t    </table>                     \n");
      out.write("                    \n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- /.start-add-user-modal-->\n");
      out.write("        <div class=\"modal fade\" id=\"addUserModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("          <div class=\"modal-dialog modal-primary modal-lg\" role=\"document\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("              <div class=\"modal-header\">\n");
      out.write("                <h4 class=\"modal-title\">New user </h4>\n");
      out.write("                <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                  <span aria-hidden=\"true\">X</span>\n");
      out.write("                </button>\n");
      out.write("              </div>\n");
      out.write("\t\t\t        <!-- /.modal-header-->\n");
      out.write("\n");
      out.write("              <div class=\"modal-body\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"form-group col-sm-4 col-lg-4\">\n");
      out.write("                    <label for=\"first_name\"><strong>First name</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" id=\"first_name\" placeholder=\"Enter first name\" />\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"form-group col-sm-4 col-lg-4\">\n");
      out.write("                    <label for=\"middle_name\"><strong>Middle name</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" id=\"middle_name\" placeholder=\"Enter middle name\" />\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"form-group col-sm-4 col-lg-4\">\n");
      out.write("                    <label  for=\"last_name\"><strong>Last name</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" id=\"last_name\" placeholder=\"Enter last name\" />\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"form-group col-sm-6 col-lg-6\">\n");
      out.write("                    <label for=\"email\"><strong>Email</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" id=\"email\" placeholder=\"Enter user email\" />\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"form-group col-sm-6 col-lg-6\">\n");
      out.write("                    <label for=\"phoneNumber\"><strong>Phone #</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" id=\"phoneNumber\" placeholder=\"Enter phone number \" />\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"form-group col-sm-6 col-lg-6\">\n");
      out.write("                    <label for=\"userPassword\"><strong>User Password</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"password\" id=\"password\" placeholder=\"\"  onkeyup=\"passwordCheck(this.value, 'password')\"/>\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"form-group col-sm-6 col-lg-6\">\n");
      out.write("                    <label for=\"reUserPassword\"><strong>Re-type password</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"password\" id=\"confirm_password\" placeholder=\"\" />\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write(" \t\t\t\t<div id=\"pmatch\" style=\"color:red; display:none\" >Passwords dont match!</div>    <br>\n");
      out.write("                <div class=\"row\">\n");
      out.write("\n");
      out.write("                  <div class=\"form-group col-sm-4 col-lg-4\">\n");
      out.write("                    <label for=\"role\"><strong>Role:</strong></label>\n");
      out.write("                  <select class=\"form-control\" id=\"region\" name=\"region\">\n");
      out.write("\t \t\t\t<option value=\"\">-- Roles -- </option>\n");
      out.write(" \t \t\t\t");

 	 			
				try{
					File errorLogs = null;
	                String errorLogFile = Utility.getPath();
	                errorLogs = new File(errorLogFile);
							                    
				java.util.List<Roles> list = Roles.GetRolesList();
							
				for (int i = 0; i < list.size(); i++){
				
      out.write("\n");
      out.write("\t\t\t\t<option value=\"");
 out.print(list.get(i).getRoleID());
      out.write('"');
      out.write('>');
      out.write(' ');
 out.print(list.get(i).getRoles_name()); 
      out.write(" </option>\t\t\t\t\t\t\t\t      \n");
      out.write("\t\t\t\t ");

				}
				}catch(Exception er){
				//ErrorLogsAppender.appendException("User.jsp page", er, errorLogs);
				}
 	 			
      out.write("\n");
      out.write("\t \t\t\t</select>\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\t\t\t        <!-- /.modal-body -->\n");
      out.write("\t\t\t  \n");
      out.write("              <div class=\"modal-footer\">\n");
      out.write("                <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                <button class=\"btn btn-primary\" type=\"submit\" onClick=\"addUser();\">Save changes</button>\n");
      out.write("              </div>\n");
      out.write("\t\t\t        <!-- /.modal-footer -->\n");
      out.write("\t\t\t  \n");
      out.write("            </div>\n");
      out.write("            <!-- /.modal-content-->\n");
      out.write("          </div>\n");
      out.write("          <!-- /.modal-dialog-->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.end-add-user-modal-->\n");
      out.write("\n");
      out.write("        <!-- /.start-edit-user-modal-->\n");
      out.write("        <div class=\"modal fade\" id=\"editUserModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("          <div class=\"modal-dialog modal-primary modal-lg\" role=\"document\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("              <div class=\"modal-header\">\n");
      out.write("                <h4 class=\"modal-title\">Edit user </h4>\n");
      out.write("                <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                  <span aria-hidden=\"true\">X</span>\n");
      out.write("                </button>\n");
      out.write("              </div>\n");
      out.write("\t\t\t        <!-- /.modal-header-->\n");
      out.write("\t\t\t  \n");
      out.write("              <div class=\"modal-body\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"form-group col-sm-4\">\n");
      out.write("                    <label for=\"firstName\"><strong>First name</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" id=\"firstName\" placeholder=\"Enter first name\" />\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"form-group col-sm-4\">\n");
      out.write("                    <label for=\"middleName\"><strong>Middle name</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" id=\"middleName\" placeholder=\"Enter middle name\" />\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"form-group col-sm-4\">\n");
      out.write("                    <label  for=\"lastName\"><strong>Last name</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" id=\"lastName\" placeholder=\"Enter last name\" />\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t        <div class=\"row\">\n");
      out.write("                  <div class=\"form-group col-sm-6 col-lg-6\">\n");
      out.write("                    <label for=\"email\"><strong>Email</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" id=\"email\" placeholder=\"Enter user email\" />\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"form-group col-sm-6 col-lg-6\">\n");
      out.write("                    <label for=\"phoneNumber\"><strong>Phone #</strong></label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" id=\"phoneNumber\" placeholder=\"Enter phone number \" />\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"form-group col-sm-4 col-lg-4\">\n");
      out.write("                    <label for=\"role\"><strong>Role:</strong></label>\n");
      out.write("                    <select class=\"form-control\" id=\"role\" name=\"role\">\n");
      out.write("                      <option value=\"0\">Please select</option>\n");
      out.write("                      <option value=\"administrator\">Administrator</option>\n");
      out.write("                      <option value=\"juniorOperator\">Junior Operator</option>\n");
      out.write("                      <option value=\"seniorOperator\">Senior Operator</option>\n");
      out.write("                    </select>\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"form-group col-sm-4 col-lg-4\">\n");
      out.write("                    <label for=\"site\"><strong>Site/Region:</strong></label>\n");
      out.write("                    <select class=\"form-control\" id=\"site\" name=\"site\">\n");
      out.write("                      <option value=\"0\">Please select</option>\n");
      out.write("                      <option value=\"1\">Arusha</option>\n");
      out.write("                      <option value=\"2\">Dar-es-salaam</option>\n");
      out.write("                      <option value=\"3\">Mwanza</option>\n");
      out.write("                    </select>\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"form-group col-sm-4 col-lg-4\">\n");
      out.write("                    <label for=\"status\"><strong>Status:</strong></label>\n");
      out.write("                    <select class=\"form-control\" id=\"status\" name=\"status\">\n");
      out.write("                      <option value=\"0\">Active</option>\n");
      out.write("                      <option value=\"1\">Inactive</option>\n");
      out.write("                    </select>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\t\t\t        <!-- /.modal-body -->\n");
      out.write("\t\t\t  \n");
      out.write("              <div class=\"modal-footer\">\n");
      out.write("                <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                <button class=\"btn btn-primary\" type=\"submit\">Save changes</button>\n");
      out.write("              </div>\n");
      out.write("\t\t\t        <!-- /.modal-footer -->\n");
      out.write("\t\t\t  \n");
      out.write("            </div>\n");
      out.write("            <!-- /.modal-content-->\n");
      out.write("          </div>\n");
      out.write("          <!-- /.modal-dialog-->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.end-edit-user-modal-->\n");
      out.write("\n");
      out.write("\t\t<!-- /.start-view-modal-->\n");
      out.write("        <div class=\"modal fade\" id=\"viewUserModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("          <div class=\"modal-dialog modal-success\" role=\"document\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("              <div class=\"modal-header\">\n");
      out.write("                <h4 class=\"modal-title\">User details</h4>\n");
      out.write("                <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                  <span aria-hidden=\"true\">X</span>\n");
      out.write("                </button>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"modal-body\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                  <div class=\"card-header\">Roger P. Njau</div>\n");
      out.write("                  <div class=\"card-body\">\n");
      out.write("                    <dl class=\"row\">\n");
      out.write("                      <dt class=\"col-sm-3\">Email:</dt>\n");
      out.write("                      <dd class=\"col-sm-9\">roger.njau@tcra.go.tz</dd>\n");
      out.write("                      <dt class=\"col-sm-3\">Phone #:</dt>\n");
      out.write("                      <dd class=\"col-sm-9\"> 0780-000000</dd>\n");
      out.write("                      <dt class=\"col-sm-3\">Site/Region:</dt>\n");
      out.write("                      <dd class=\"col-sm-9\">Dar-es-salaam</dd>\n");
      out.write("                      <dt class=\"col-sm-3\">Role:</dt>\n");
      out.write("                      <dd class=\"col-sm-9\">System Administrator.</dd>\n");
      out.write("                      <dt class=\"col-sm-3 text-truncate\">Status:</dt>\n");
      out.write("                      <dd class=\"col-sm-9\"><span class=\"badge badge-success\">Active</span> <span class=\"badge badge-danger\">Inactive</span></dd>\n");
      out.write("                    </dl>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Close</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t  </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("              \n");
      out.write("            </div>\n");
      out.write("            <!-- /.modal-content-->\n");
      out.write("          </div>\n");
      out.write("          <!-- /.modal-dialog-->\n");
      out.write("        <!-- /.end-view-modal-->\n");
      out.write("\t\t\n");
      out.write("      </main>\n");
      out.write("\n");
      out.write("<!-- Start AsideMenu View -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/asideMenuView.jsp", out, false);
      out.write("\n");
      out.write("<!-- End AsideMenu View --> \n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("<!-- Start Top header View -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/footer.jsp", out, false);
      out.write("\n");
      out.write("<!-- End Top Header View -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("$(document).ready(function() {\n");
      out.write("\n");
      out.write("    $('#datatables').DataTable();\n");
      out.write("\n");
      out.write("    });\n");
      out.write("\n");
      out.write("  </script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
