/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-11-28 07:19:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"./\">\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"CoreUI - Open Source Bootstrap Admin Template\">\r\n");
      out.write("    <meta name=\"author\" content=\"Åukasz Holeczek\">\r\n");
      out.write("    <meta name=\"keyword\" content=\"Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard\">\r\n");
      out.write("    <title>Tanzania Content Monitoring System</title>\r\n");
      out.write("    <!-- Icons-->\r\n");
      out.write("    <link href=\"css/dataTables.bootstrap4.min.css\" rel=\"stylesheet\"> \r\n");
      out.write("    <link rel=\"icon\" type=\"image/ico\" href=\"./img/favicon.ico\" sizes=\"any\" />\r\n");
      out.write("    <link href=\"node_modules/@coreui/icons/css/coreui-icons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"node_modules/flag-icon-css/css/flag-icon.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"node_modules/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"node_modules/simple-line-icons/css/simple-line-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Main styles for this application-->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"vendors/pace-progress/css/pace.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- DataTable styles for this application-\r\n");
      out.write("    <link href=\"css/dataTables.bootstrap4.min.css\" rel=\"stylesheet\"> \r\n");
      out.write("    -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Our custom stylesheet for this application-->\r\n");
      out.write("    <link href=\"css/ourcustom.css\" rel=\"stylesheet\"> \r\n");
      out.write("    \r\n");
      out.write("    <!-- DataTable styles for this application-->\r\n");
      out.write("    <link href=\"css/newjquery.dataTables.min.css\" rel=\"stylesheet\"> \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- TCMS icon in the Title-->\r\n");
      out.write("    <link rel=\"icon\" href=\"img/tcra-logo.png\" width=\"100%\" height=\"100%\" class=\"img-fluid\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Global site tag (gtag.js) - Google Analytics-->\r\n");
      out.write("    <script async=\"\" src=\"https://www.googletagmanager.com/gtag/js?id=UA-118965717-3\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("      window.dataLayer = window.dataLayer || [];\r\n");
      out.write("\r\n");
      out.write("      function gtag() {\r\n");
      out.write("        dataLayer.push(arguments);\r\n");
      out.write("      }\r\n");
      out.write("      gtag('js', new Date());\r\n");
      out.write("      // Shared ID\r\n");
      out.write("      gtag('config', 'UA-118965717-3');\r\n");
      out.write("      // Bootstrap ID\r\n");
      out.write("      gtag('config', 'UA-118965717-5');\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body class=\"app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show\">\r\n");
      out.write("    <header class=\"app-header navbar\">\r\n");
      out.write("      <button class=\"navbar-toggler sidebar-toggler d-lg-none mr-auto\" type=\"button\" data-toggle=\"sidebar-show\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("        <img class=\"navbar-brand-full\" src=\"img/brand/logos.svg\" width=\"89\" height=\"25\" alt=\"TCMS Logo\">\r\n");
      out.write("        <img class=\"navbar-brand-minimized\" src=\"img/brand/sygnet.svg\" width=\"30\" height=\"30\" alt=\"TCMS Logo\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <button class=\"navbar-toggler sidebar-toggler d-md-down-none\" type=\"button\" data-toggle=\"sidebar-lg-show\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
