/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-11-28 09:56:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import tcms.presentation.*;

public final class channel_002dtv_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("tcms.presentation");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Start header -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/header.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End header -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start Top header View -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/topView.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Top Header View -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start SideBar View -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/sideView.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End SideBar View -->\r\n");
      out.write("\r\n");
      out.write("      <main class=\"main\">\r\n");
      out.write("        <!-- Breadcrumb-->\r\n");
      out.write("        <ol class=\"breadcrumb\">\r\n");
      out.write("          <li class=\"breadcrumb-item\">Home</li>\r\n");
      out.write("          <li class=\"breadcrumb-item\">\r\n");
      out.write("            Content\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"breadcrumb-item\">\r\n");
      out.write("          <a href=\"channel-tv.jsp\">Television</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("        </ol>\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"animated fadeIn\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-4 col-lg-2\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-header\">\r\n");
      out.write("                        </i> Channels\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                        <ul class=\"list-group\">\r\n");
      out.write("                            <li class=\"list-group-item\">AZAM TV</li>\r\n");
      out.write("                            <li class=\"list-group-item active\">ITV</li>\r\n");
      out.write("                            <li class=\"list-group-item\">TBC 1</li>\r\n");
      out.write("                            <li class=\"list-group-item\">TBC 2</li>\r\n");
      out.write("                            <li class=\"list-group-item\">WASAFI TV</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-8 col-lg-10\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <!-- /.col-->\r\n");
      out.write("                        <div class=\"col-sm-12 col-lg-6 mb-2\">\r\n");
      out.write("                          <div id=\"media-player\">\r\n");
      out.write("                           ");
 java.util.List<Content> contentList = Content.GetContent(); 
                            
                            for(int i=0; i<contentList.size(); i++) { 
                           
                            
      out.write("\r\n");
      out.write("                            <video id=\"classic-video\" class=\"media-video\" controls>\r\n");
      out.write("                           \r\n");
      out.write("                                <source src=\"../");
out.print(contentList.get(i).getFile_path_file_name()); 
      out.write("\" type=\"video/mp4\">\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                                    Your browser does not support the video element.\r\n");
      out.write("                            </video>\r\n");
      out.write("                            <!-- <div id=\"media-controls\">\r\n");
      out.write("                              <button id=\"play-pause-button\" class=\"play\" title=\"PLAY\" onclick=\"togglePlayPause();\">Play\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"stop-button\" class=\"stop\" title=\"STOP\" onclick=\"stopPlayer();\">Stop\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"volume-inc-button\" class=\"volume-plus\" title=\"INCREASE VOLUME\" onclick='changeVolume(\"+\");'>Increase volume\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"volume-dec-button\" class=\"volume-minus\" title=\"DECREASE VOLUME\" onclick='changeVolume(\"-\");'>Decrease volume\r\n");
      out.write("                              </button>\r\n");
      out.write("                            </div> -->\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /.col-->\r\n");
      out.write("                        <div class=\"col-sm-12 col-lg-6 mb-2\">\r\n");
      out.write("                            <video id=\"classic-video\" class=\"media-video\" controls>\r\n");
      out.write("                                <source src=\"vid/vid1.mp4\" type=\"video/mp4\">\r\n");
      out.write("                                    Your browser does not support the video element.\r\n");
      out.write("                            </video>\r\n");
      out.write("\r\n");
      out.write("                            <!-- <div id=\"media-controls\">\r\n");
      out.write("                              <button id=\"play-pause-button\" class=\"play\" title=\"play\" onclick=\"togglePlayPause();\">\r\n");
      out.write("                                Play\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"stop-button\" class=\"stop\" title=\"stop\" onclick=\"stopPlayer();\">\r\n");
      out.write("                              Stop\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"volume-inc-button\" class=\"volume-plus\" title=\"increase volume\" onclick='changeVolume(\"+\");'>\r\n");
      out.write("                              Increase volume\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"volume-dec-button\" class=\"volume-minus\" title=\"decrease volume\" onclick='changeVolume(\"-\");'>\r\n");
      out.write("                              Decrease volume\r\n");
      out.write("                              </button>\r\n");
      out.write("                            </div> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /.col-->\r\n");
      out.write("                        <div class=\"col-sm-12 col-lg-6 mb-2\">\r\n");
      out.write("                            <video id=\"classic-video\" class=\"media-video\" controls>\r\n");
      out.write("                            \r\n");
      out.write("                                <source src=\"vid/vid2.mp4\" type=\"video/mp4\">\r\n");
      out.write("                                    Your browser does not support the video element.\r\n");
      out.write("                            </video>\r\n");
      out.write("\r\n");
      out.write("                            <!-- <div id=\"media-controls\">\r\n");
      out.write("                              <button id=\"play-pause-button\" class=\"play\" title=\"play\" onclick=\"togglePlayPause();\">\r\n");
      out.write("                                Play\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"stop-button\" class=\"stop\" title=\"stop\" onclick=\"stopPlayer();\">\r\n");
      out.write("                              Stop\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"volume-inc-button\" class=\"volume-plus\" title=\"increase volume\" onclick='changeVolume(\"+\");'>\r\n");
      out.write("                              Increase volume\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"volume-dec-button\" class=\"volume-minus\" title=\"decrease volume\" onclick='changeVolume(\"-\");'>\r\n");
      out.write("                              Decrease volume\r\n");
      out.write("                              </button>\r\n");
      out.write("                            </div> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /.col-->\r\n");
      out.write("                        <div class=\"col-sm-12 col-lg-6\">\r\n");
      out.write("                          <div id=\"media-player\">\r\n");
      out.write("                            <video id=\"classic-video\" class=\"media-video\" controls>\r\n");
      out.write("                                <source src=\"vid/vid2.mp4\" type=\"video/mp4\">\r\n");
      out.write("                                    Your browser does not support the video element.\r\n");
      out.write("                            </video>\r\n");
      out.write("\r\n");
      out.write("                            <!-- <div id=\"media-controls\">\r\n");
      out.write("                              <button id=\"play-pause-button\" class=\"play\" title=\"play\" onclick=\"togglePlayPause();\">\r\n");
      out.write("                                Play\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"stop-button\" class=\"stop\" title=\"stop\" onclick=\"stopPlayer();\">\r\n");
      out.write("                              Stop\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"volume-inc-button\" class=\"volume-plus\" title=\"increase volume\" onclick=\"changeVolume(+);\">\r\n");
      out.write("                              Increase volume\r\n");
      out.write("                              </button>\r\n");
      out.write("                              <button id=\"volume-dec-button\" class=\"volume-minus\" title=\"decrease volume\" onclick=\"changeVolume(-);\">\r\n");
      out.write("                              Decrease volume\r\n");
      out.write("                              </button>\r\n");
      out.write("                            </div> -->\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /.col-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </main>\r\n");
      out.write("\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("        //$(document).ready(function(){\r\n");
      out.write("          /* document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("            initialiseMediaPlayer(); }, \r\n");
      out.write("          false);\r\n");
      out.write("\r\n");
      out.write("          var mediaPlayer; */\r\n");
      out.write("\r\n");
      out.write("          //var \r\n");
      out.write("\r\n");
      out.write("          //const btnPlay = document.querySelector('#play-pause-button');\r\n");
      out.write("\r\n");
      out.write("          /* const videoElement = document.querySelector('.media-video'); */\r\n");
      out.write("\r\n");
      out.write("          // const incVolume = document.querySelector('.volume-plus');\r\n");
      out.write("\r\n");
      out.write("          // const decVolume = document.querySelector('.volume-minus');\r\n");
      out.write("          \r\n");
      out.write("          /* function initialiseMediaPlayer() {\r\n");
      out.write("            mediaPlayer = document.getElementsByClassName('media-video');\r\n");
      out.write("\r\n");
      out.write("            console.log(mediaPlayer);\r\n");
      out.write("            for(var i = 0; i < mediaPlayer.length; i++)\r\n");
      out.write("              mediaPlayer[i].controls = false;\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          function togglePlayPause(){\r\n");
      out.write("            var btn = document.getElementById('play-pause-button');\r\n");
      out.write("            if(videoElement.paused || videoElement.ended){\r\n");
      out.write("              btn.title = 'PAUSE';\r\n");
      out.write("              btn.innerHTML = 'Pause';\r\n");
      out.write("              btn.className = 'Pause';\r\n");
      out.write("              console.log(\"Play\");\r\n");
      out.write("              mediaPlayer[0].play();\r\n");
      out.write("            }else{\r\n");
      out.write("              btn.title = 'PLAY';\r\n");
      out.write("              btn.innerHTML = 'Play';\r\n");
      out.write("              btn.className = 'Play';\r\n");
      out.write("              console.log(\"Pause\");\r\n");
      out.write("              mediaPlayer[0].pause();\r\n");
      out.write("            }\r\n");
      out.write("            //console.log(mediaPlayer);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          function stopPlayer(){\r\n");
      out.write("            mediaPlayer[0].pause()\r\n");
      out.write("            mediaPlayer[0].currentTime = 0;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          function changeVolume(direction){\r\n");
      out.write("            \r\n");
      out.write("            if(direction == '+')\r\n");
      out.write("              mediaPlayer[0].volume += mediaPlayer[0].volume == 1 ? 0 : 0.1;\r\n");
      out.write("            else mediaPlayer[0].volume -= (mediaPlayer[0].volume == 0 ? 0: 0.1);\r\n");
      out.write("\r\n");
      out.write("            mediaPlayer[0].volume = parseFloat(mediaPlayer[0].volume).toFixed(1);\r\n");
      out.write("            \r\n");
      out.write("          } */\r\n");
      out.write("      </script>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<!-- Start AsideMenu View -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/asideMenuView.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End AsideMenu View --> \r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("<!-- Start Footer View -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Footer View -->\r\n");
      out.write("\t\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
