/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2020-04-01 16:33:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import java.util.Vector;
import java.util.Vector;
import java.sql.*;
import javax.sql.*;
import tcms.csp.*;
import org.apache.commons.codec.digest.*;
import tcms.errorLogs.*;
import java.util.*;
import java.io.*;

public final class csp_002dapproved_002dpl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("tcms.errorLogs");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("tcms.csp");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("org.apache.commons.codec.digest");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


response.setHeader("Cache-control", "no-cache");
response.setHeader("Cache-control", "no-store");
response.setHeader("Pragma", "no-cache");
response.setDateHeader("Expire",0);

if (session.getAttribute("channelID") != null ) {

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Start Header -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "csp-includes/header.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getDay(){\r\n");
      out.write("\r\n");
      out.write("\tvar sel = document.getElementById(\"day\");\r\n");
      out.write("\tvar day= sel.options[sel.selectedIndex].text;\r\n");
      out.write("\tvar channelID = document.getElementById('channelID').value;\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById('dayName').value = day;\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({ \r\n");
      out.write("\t     type: \"GET\",\r\n");
      out.write("\t      url: \"csp-get-approved-program.jsp\", //this is my servlet\r\n");
      out.write("\t      dataType: \"json\",\r\n");
      out.write("\t       data: {\r\n");
      out.write("\t\t\t  day: day,\r\n");
      out.write("\t\t\t  channelID: channelID\r\n");
      out.write("\t           }, \r\n");
      out.write("\t\t          success: function(programList){  \r\n");
      out.write("\t\t\t          var s = '';\r\n");
      out.write("\t\t\t          s += '<div class=\"fresh-datatables\">';\r\n");
      out.write("\t\t\t          s += '<table id=\"datatables\" class=\"table table-striped table-no-bordered table-hover\" cellspacing=\"0\" width=\"100%\" style=\"width:100%\">';\r\n");
      out.write("\t\t\t          s += '<thead>';\r\n");
      out.write("\t\t\t          s += '<tr>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" style=\"width:12%\">Time</th>';\t\t\t          \r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" >Name</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" >Main Objective</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" >Target Audience</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" >Expectetions</th>';\r\n");
      out.write("\t\t\t         // s += '<th>Status</th>';\r\n");
      out.write("\t\t\t          //s += '<th>Actions</th>';\r\n");
      out.write("\t\t\t          s += '</tr>';\r\n");
      out.write("\t\t\t          s += '</thead>';\r\n");
      out.write("\t\t\t          s += '<tfoot>';\r\n");
      out.write("\t\t\t          s += '<tr>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" style=\"width:12%\">Time</th>';\t\t\t          \r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" >Name</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" >Main Objective</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" >Target Audience</th>';\r\n");
      out.write("\t\t\t          s += '<th class=\"no-sort\" >Expectetions</th>'\r\n");
      out.write("\t\t\t         // s += '<th>Status</th>';\r\n");
      out.write("\t\t\t          //s += '<th>Actions</th>';\r\n");
      out.write("\t\t\t          s += '</tr>';\r\n");
      out.write("\t\t\t          s += '</tfoot>';\r\n");
      out.write("\t\t\t          s += '<tbody >';\r\n");
      out.write("\t\t\t          $.each(programList.data, function(index,programList) {        \r\n");
      out.write("\t\t\t              //alert(equipmentList.make+\" -- \"+equipmentList.model+\" -- \"+equipmentList.country+\" -- \"+equipmentList.equipmentType+\" -- \"+equipmentList.cdate)\r\n");
      out.write("\t\t\t                s += '<tr>';\r\n");
      out.write("\t\t\t\t\t\t    s += '<td>' + programList.time + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + programList.programeName + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + programList.programObjective + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + programList.targetAudience + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<td>' + programList.expectedArchivement + '<input type=\"hidden\" id=\"entryDate\" value=\"'+programList.entryDate+'\"></td>';\r\n");
      out.write("\t\t\t\t\t\t\t//s += '<td>' + programList.status + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\t//s += '<td> <a class=\"btn btn-primary btn-circle btn-sm\" href=\"#editProgrammeModal\" data-toggle=\"modal\" title=\"EDIT\"  onClick=\"editProgram('+ programList.id +');\" ><i class=\"fas fa-pencil-alt\"></i></a>&nbsp; <a class=\"btn btn-danger btn-circle btn-sm\" href=\"#editProgrammeModal\" data-toggle=\"modal\" title=\"DELETE\"  onClick=\"editProgram(' + programList.id + ');\"><i class=\"fas fa-trash\"></i></a></td>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '</tr>';\r\n");
      out.write("\t\t\t          });\t\r\n");
      out.write("\t\t\t      \t\r\n");
      out.write("\t\t\t          s += '</tbody>';\r\n");
      out.write("\t\t\t          s += '</table>';\r\n");
      out.write("\t\t\t          s += '</div>';\r\n");
      out.write("\t\t\t          $('#result').html(s);\r\n");
      out.write("\t\t\t          $('#datatables').DataTable( {\r\n");
      out.write("                          \"order\": [],\r\n");
      out.write("                           \"columnDefs\": [{\r\n");
      out.write("                               \"targets\": 'no-sort',\r\n");
      out.write("                               \"orderable\": false,\r\n");
      out.write("                    \t\t\t }]\r\n");
      out.write("                   \t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t   });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"output\"></div>\r\n");
      out.write("<input type=\"hidden\" id=\"channelID\" value=\"");
 out.print(session.getAttribute("channelID")); 
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Page Wrapper -->\r\n");
      out.write("  <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Sidebar -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "csp-includes/sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- End Sidebar -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Content Wrapper -->\r\n");
      out.write("    <div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Main Content -->\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Start Topbar -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "csp-includes/csp-home-topbar.jsp", out, false);
      out.write("\r\n");
      out.write("        <!-- End Topbar -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Begin Page Content -->\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"card shadow mb-4\">\r\n");
      out.write("            <div class=\"card-header py-3\">\r\n");
      out.write("                <!--<div class=\"clearfix\"> -->\r\n");
      out.write("                <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                \r\n");
      out.write("                     <h5> <i class=\"fas fa-fw fa-clock\"></i> CURRENT PROGRAM LINE-UP  </h5>\r\n");
      out.write("                   <div class=\"dropdown\">\r\n");
      out.write("    \r\n");
      out.write("    <select class=\"form-control rounded-pill\" id=\"day\" name=\"day\"onChange=\"getDay();\">\r\n");
      out.write("\t\t");

	 		File errorLogs = null;
            String errorLogFile = Utility.getPath();
            errorLogs = new File(errorLogFile);
			try{
						                    
			java.util.List<Days> contentList = Days.getDays();
						
			for (int i = 0; i < contentList.size(); i++){
				
			
      out.write("\r\n");
      out.write("\t\t\t<option value=\"");
 out.print(contentList.get(i).getId());
      out.write('"');
      out.write('>');
      out.write(' ');
 out.print(contentList.get(i).getDay()); 
      out.write(" </option>\t\t\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t ");

			}
			}catch(Exception er){
				er.printStackTrace();
			ErrorLogsAppender.appendException("Search.jsp page", er, errorLogs);
			}
		
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("</div> \r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("                <!--</div> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<div id=\"result\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\t\t  <div class=\"d-flex justify-content-end\">\r\n");
      out.write("          \r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"outputProgram\"></div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.container-fluid -->\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- End of Main Content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Scroll to Top Button-->\r\n");
      out.write("  <a class=\"scroll-to-top rounded\" href=\"#page-top\">\r\n");
      out.write("    <i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("  </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Add Programme Modal-->\r\n");
      out.write("   <div class=\"modal fade\" id=\"addProgrammeModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"exampleModalLabel\">Create new Programme?</h5>\r\n");
      out.write("                <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                \t\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <label for=\"programme-name\">Programme name</label>\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" id=\"program-name\" name =\"program-name\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                      <div class=\"form-group col-md-6\">\r\n");
      out.write("                        <label for=\"start-time\">Start time</label>\r\n");
      out.write("                        <input type=\"time\" class=\"form-control\" id=\"start-time\" required>\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"form-group col-md-6\">\r\n");
      out.write("                        <label for=\"end-time\">End time</label>\r\n");
      out.write("                        <input type=\"time\" class=\"form-control\" id=\"end-time\" required>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                      <div class=\"form-group col-6\">\r\n");
      out.write("                        <label>Objectives</label>\r\n");
      out.write("                        \r\n");
      out.write("                        <select class=\"selectpicker\" id=\"objective\">\r\n");
      out.write("                          ");

							try{
										                    
							java.util.List<Objctives> list = Objctives.getObjective();
										
							for (int i = 0; i < list.size(); i++){
								
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
 out.print(list.get(i).getId());
      out.write('"');
      out.write('>');
      out.write(' ');
 out.print(list.get(i).getObjectiveName()); 
      out.write(" </option>\t\t\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t\t ");

							}
							}catch(Exception er){
								er.printStackTrace();
							ErrorLogsAppender.appendException("Search.jsp page", er, errorLogs);
							}
						
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                    \r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"form-group col-6\">\r\n");
      out.write("                        <label>Target Audience</label>\r\n");
      out.write("                         <div class=\"dropdown\">\r\n");
      out.write("                        <select class=\"selectpicker\" id=\"audience\">\r\n");
      out.write("                           ");

							try{
										                    
							java.util.List<TargetAudience> list = TargetAudience.getTargetAudience();
										
							for (int i = 0; i < list.size(); i++){
								
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
 out.print(list.get(i).getId());
      out.write('"');
      out.write('>');
      out.write(' ');
 out.print(list.get(i).getTargetAudienceName()); 
      out.write(" </option>\t\t\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t\t ");

							}
							}catch(Exception er){
								er.printStackTrace();
							ErrorLogsAppender.appendException("Search.jsp page", er, errorLogs);
							}
						
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <label for=\"programme-name\">Expectations</label>\r\n");
      out.write("                      <textarea class=\"form-control\" id=\"expectation\" rows=\"2\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                  <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                  <button class=\"btn btn-primary\" onClick=\"newProgram();\">Submit</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Add Programme Modal-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Add Programme Modal-->\r\n");
      out.write("   <div class=\"modal fade\" id=\"addGuideModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"exampleModalLabel\"><b>Publish Daily Programs</b></h5>\r\n");
      out.write("                <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                  <label>Are you sure you want to publish <input type=\"text\" id=\"dayName\">programs ?</label>\r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                  <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                   <button class=\"btn btn-primary\" type=\"button\" onClick=\"publisProgram();\" data-dismiss=\"modal\">Yes</button>\r\n");
      out.write("                 \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Add Programme Modal-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Edit Programme Modal-->\r\n");
      out.write("   <div class=\"modal fade\" id=\"editProgrammeModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"exampleModalLabel\">Edit Programme?</h5>\r\n");
      out.write("                <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                <input type=\"hidden\" id=\"programmeID\" name=\"programmeID\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <label for=\"programme-name\">Programme name</label>\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" id=\"programme-name2\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                      <div class=\"form-group col-md-6\">\r\n");
      out.write("                        <label for=\"start-time\">Start time</label>\r\n");
      out.write("                        <input type=\"time\" class=\"form-control\" id=\"start-time2\" required>\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"form-group col-md-6\">\r\n");
      out.write("                        <label for=\"end-time\">End time</label>\r\n");
      out.write("                        <input type=\"time\" class=\"form-control\" id=\"end-time2\" required>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                      <div class=\"form-group col-6\">\r\n");
      out.write("                        <label>Objective</label>\r\n");
      out.write("                        <input type=\"text\" id=\"objective2\" class=\"selectpicker\" />\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"form-group col-6\">\r\n");
      out.write("                        <label>Target Audience</label>\r\n");
      out.write("                        <input type=\"text\" id=\"audience2\" class=\"selectpicker\" />\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <label for=\"programme-name\">Expectations</label>\r\n");
      out.write("                      <textarea class=\"form-control\" id=\"achievement2\" rows=\"2\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                  <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                  <button class=\"btn btn-primary\" type=\"button\" onClick=\"updateProgram();\" data-dismiss=\"modal\">Update</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Edit Programme Modal-->\r\n");
      out.write("    \r\n");
      out.write("      <!-- Start Delete Program Lineup Modal-->\r\n");
      out.write("   <div class=\"modal fade\" id=\"deleteProgrammeModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">      \r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"exampleModalLabel\">Delete a program</h5>\r\n");
      out.write("                <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">Are you sure you want to delete this program ?</div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                <a class=\"btn btn-danger\" href=\"login.html\">Delete</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   <!-- End Delete Program Lineup Modal-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Logout Modal-->\r\n");
      out.write("   <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\r\n");
      out.write("                <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                <a class=\"btn btn-primary\" href=\"login.html\">Logout</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Logout Modal-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Start Footer -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "csp-includes/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- End Footer -->\r\n");
      out.write(" \r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t    $('#datatables').DataTable( {\r\n");
      out.write("\t        dom: 'Bfrtip',\r\n");
      out.write("\t        buttons: [\r\n");
      out.write("\t            'copy', 'csv', 'excel', 'pdf', 'print'\r\n");
      out.write("\t        ]\r\n");
      out.write("\t    } );\r\n");
      out.write("\t} );\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t getDay();\r\n");
      out.write("\t\t});\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("      ");

} else {
	session.setAttribute("channelID", null);
	session.setAttribute("channel_name", null);
	session.setAttribute("company_name", null);
	session.setAttribute("user_id", null);
	session.setAttribute("company_address", null);
	session.setAttribute("contact_person", null);
	session.setAttribute("mobile_phone", null);
	session.setAttribute("email", null);
    session.invalidate();
	response.sendRedirect("index.jsp");
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
