/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-11-22 05:52:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Start header -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/header.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End header -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start Top header View -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/topView.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Top Header View -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start SideBar View -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/sideView.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End SideBar View -->\r\n");
      out.write("\r\n");
      out.write("      <main class=\"main\">\r\n");
      out.write("         <!-- Breadcrumb-->\r\n");
      out.write("         <ol class=\"breadcrumb\">\r\n");
      out.write("          <li class=\"breadcrumb-item\">Home</li>\r\n");
      out.write("          <li class=\"breadcrumb-item\">\r\n");
      out.write("            Settings\r\n");
      out.write("          </li>   \r\n");
      out.write("          <li class=\"breadcrumb-item\">\r\n");
      out.write("            <a href=\"regions.jsp\">Regions</a>\r\n");
      out.write("          </li>   \r\n");
      out.write("        </ol>        \r\n");
      out.write("        <!-- Breadcrumb-->\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"animated fadeIn\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-12 col-xl-12\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-header\">\r\n");
      out.write("                    <i class=\"fa fa-align-justify\"></i> List of Regions         \r\n");
      out.write("                    <div class=\"card-header-actions\">\r\n");
      out.write("                    <button class=\"btn btn-pill btn-block btn-primary mb-1\" type=\"button\" data-toggle=\"modal\" data-target=\"#addRegionsDetailsModal\">\r\n");
      out.write("                    <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                    <b>Add Region</b>\r\n");
      out.write("                     </button>                    \r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                   \r\n");
      out.write("                    <table id=\"datatables\" class=\"table table-striped table-no-bordered table-hover\" cellspacing=\"0\" width=\"100%\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>Region</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>Zone</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"disabled-sorting\">Actions</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                        <th>Region</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>Zone</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"disabled-sorting\">Actions</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t          <!-- Start of the Table Body -->\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>DAR-ES-SALAAM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Eastern Zone</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>                       \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-info\" href=\"#editRegionsDetailsModal\" data-toggle=\"modal\" title=\"EDIT\">\r\n");
      out.write("                          <i class=\"fa fa-edit\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a class=\"btn btn-danger\"  href=\"#deleteRegionModal\" data-toggle=\"modal\"  title=\"DELETE\">\r\n");
      out.write("                          <i class=\"fa fa-trash-o\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- End of the Table Body -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   </tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </table>                     \r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("             \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </main>\r\n");
      out.write("\r\n");
      out.write("<!-- Start AsideMenu View -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/asideMenuView.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End AsideMenu View --> \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("   <!-- Start Add Region Form -->\r\n");
      out.write(" <div class=\"modal fade\" id=\"addRegionsDetailsModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-primary\" role=\"document\">\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                  <h4 class=\"modal-title\">New Region</h4>\r\n");
      out.write("                  <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">X</span>\r\n");
      out.write("                  </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <form action=\"\" method=\"post\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"role-name\"><b>Region</b></label>\r\n");
      out.write("                        <input class=\"form-control\" id=\"region\" type=\"text\" name=\"region\" placeholder=\"Enter Region..\">                      \r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"path-name\"><b>Zone Name</b></label>\r\n");
      out.write("                        <select class=\"form-control\" id=\"zone-name\">\r\n");
      out.write("                          <option  value=\"\">-- Zones --</option>\r\n");
      out.write("                          <option  value=\"Eastern Zone\">Eastern Zone</option>\r\n");
      out.write("                          <option  value=\"Northern Zone\">Northern Zone</option>\r\n");
      out.write("                          <option  value=\"Central Zone\">Central Zone</option>\r\n");
      out.write("                          <option  value=\"Southern Zone\">Southern Zone</option>\r\n");
      out.write("                          <option  value=\"Western Zone\">Western Zone</option>\r\n");
      out.write("                        </select> \r\n");
      out.write("                      </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                  <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                  <button class=\"btn btn-primary\" type=\"button\">Save</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.modal-content-->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.modal-dialog-->\r\n");
      out.write("          </div>\r\n");
      out.write("  <!-- End Add Region Form -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- Start Edit Region Form -->\r\n");
      out.write(" <div class=\"modal fade\" id=\"editRegionsDetailsModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-primary\" role=\"document\">\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                  <h4 class=\"modal-title\">Edit Region</h4>\r\n");
      out.write("                  <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">X</span>\r\n");
      out.write("                  </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <form action=\"\" method=\"post\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"role-name\"><b>Region</b></label>\r\n");
      out.write("                        <input class=\"form-control\" id=\"region\" type=\"text\" name=\"region\" placeholder=\"Enter Region..\">                      \r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"path-name\"><b>Zone Name</b></label>\r\n");
      out.write("                        <select class=\"form-control\" id=\"zone-name\">\r\n");
      out.write("                          <option  value=\"\">-- Zones --</option>\r\n");
      out.write("                          <option  value=\"Eastern Zone\">Eastern Zone</option>\r\n");
      out.write("                          <option  value=\"Northern Zone\">Northern Zone</option>\r\n");
      out.write("                          <option  value=\"Central Zone\">Central Zone</option>\r\n");
      out.write("                          <option  value=\"Southern Zone\">Southern Zone</option>\r\n");
      out.write("                          <option  value=\"Western Zone\">Western Zone</option>\r\n");
      out.write("                        </select> \r\n");
      out.write("                      </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                  <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                  <button class=\"btn btn-primary\" type=\"button\">Save</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.modal-content-->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.modal-dialog-->\r\n");
      out.write("          </div>\r\n");
      out.write("  <!-- End Edit Region Form -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start Delete Region Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"deleteRegionModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("          <div class=\"modal-dialog modal-danger\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("              <div class=\"modal-header\">\r\n");
      out.write("                <h4 class=\"modal-title\">Delete Region</h4>\r\n");
      out.write("                <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                  <span aria-hidden=\"true\">X</span>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"modal-body\">\r\n");
      out.write("                <p>Are you sure you want to <b>delete</b> this Region ?</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"modal-footer\">\r\n");
      out.write("                <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                <button class=\"btn btn-danger\" type=\"sumit\">Delete</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.modal-content-->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.modal-dialog-->\r\n");
      out.write("        </div>\r\n");
      out.write("<!-- End Delete Region Modal -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start Top header View -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- End Top Header View -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("    $('#datatables').DataTable();\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
